services:
  backoffice-server:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/backoffice_db
      - RUST_LOG=debug
      - JWKS_URL=http://rauthy:8443/jwks
      - OIDC_ISSUER=http://rauthy:8443
      - OIDC_CLIENT_ID=backoffice-frontend
      - OIDC_REDIRECT_URI=http://localhost/callback
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  backoffice-frontend:
    build:
      context: ../backoffice/frontend
      dockerfile: Dockerfile
    networks:
      - internal

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=backoffice_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d backoffice_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailcrab:
    image: marlonb/mailcrab:latest
    ports:
      - "8081:8081"
    networks:
      - internal

  rauthy:
    image: ghcr.io/sebadob/rauthy:0.34.3
    environment:
      - LOCAL_TEST=true
      - SMTP_URL=mailcrab
      - SMTP_PORT=1025
      - SMTP_DANGER_INSECURE=true
    volumes:
      - rauth_data:/app/data
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
  rauth_data:
  sozu_states:
  sozu_logs:
