[server]
pub_url = "auth.tangleweavestudios.com"
proxy_mode = true
trusted_proxies = ["127.0.0.0/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]

[database]
hiqlite = false
pg_host = "db"
pg_port = 5432
pg_user = "rauthy"
pg_db_name = "rauthy_db"

[encryption]
keys = [
    'key200426/HI8MvN7nAtS9JJB5QwpnI9X9FG12iuBxe+4W/uW8r88='
]
key_active = 'key200426'

[cluster]
node_id = 1
secret_raft = "bdd260bc80268c219b56659e016c3dab65bbaaf3d314e421f044667035c238fe"
secret_api = "0dff83499b5935a34405fb60577df8214a3358eb8ff49862131b67f2f23c0184"

[webauthn]
rp_id = "tangleweavestudios.com"
rp_origin = "https://auth.tangleweavestudios.com:443"
rp_name = "Tangleweave Auth Local"

[email]
smtp_url = "mailcrab"
smtp_port = 1025
smtp_danger_insecure = true
user = "mailcrab"      # Не 'username', а 'user'!
password = "mailcrab"
from = "admin@localhost"

[csp]
# Разрешаем встраивание только вашим поддоменам
frame_ancestors = "'self' https://*.tangleweavestudios.com"