[server]
pub_url = "auth.test.tangleweavestudios.com"
proxy_mode = true
trusted_proxies = ["127.0.0.0/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]

[database]
hiqlite = false
pg_host = "db"
pg_port = 5432
pg_user = "rauthy"
pg_db_name = "rauthy_db"

[encryption]
keys = [
    'key200426/ke7GuMleRCcjP0okyXZJwK74420z876BR3mvq/lRDGw='
]
key_active = 'key200426'

[cluster]
node_id = 1
secret_raft = "93c4b5ebffefed9946da0cfacacb8da47243598d14f416cc2022911fc6862190"
secret_api = "f9719cca8bb29832d857b4c5d1285f74f74c70b2749a3b0231c8cfb4449f9ac1"

[webauthn]
rp_id = "test.tangleweavestudios.com"
rp_origin = "https://auth.test.tangleweavestudios.com:443"
rp_name = "Tangleweave Auth Local"

[email]
smtp_url = "mailcrab"
smtp_port = 1025
smtp_danger_insecure = true
user = "mailcrab"      # Не 'username', а 'user'!
password = "mailcrab"
from = "admin@localhost"

[csp]
# Разрешаем встраивание только вашим поддоменам
frame_ancestors = "'self' https://*.test.tangleweavestudios.com"